# Generated by Django 5.0b1 on 2023-11-05 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classviewshome', '0004_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='full_name',
        ),
    ]
