# Generated by Django 5.0b1 on 2023-11-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classviewshome', '0005_remove_profile_birth_date_remove_profile_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='ФИО'),
        ),
    ]
