# Generated by Django 4.2.4 on 2023-11-07 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classviewshome', '0006_customuser_bio_profile_birth_date_profile_full_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
