# Generated by Django 4.2.4 on 2023-11-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classviewshome', '0009_usergroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='group',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Группа'),
        ),
    ]
